force-app/main/default/objects/Measurement__c/Measurement__c.object-meta.xml
<CustomObject>
    <label>Measurement</label>
    <nameField>
        <displayFormat>MI-{00000}</displayFormat>
        <label>Measurement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Measurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Measurement__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bronzed Carmel</fullName>
            </value>
            <value>
                <fullName>Delicate Whilte</fullName>
            </value>
            <value>
                <fullName>Pearl</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Measurement__c/fields/Glass_Type__c.field-meta.xml
<CustomField>
    <fullName>Glass_Type__c</fullName>
    <label>Glass Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular Clear</fullName>
                <default>true</default>
                <label>Regular Clear</label>
            </value>
            <value>
                <fullName>Low e-coated</fullName>
            </value>
            <value>
                <fullName>Obscure privacy glass</fullName>
                <isActive>false</isActive>
                <label>Obscure privacy glass</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Measurement__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Measurements</relationshipLabel>
    <relationshipName>Measurements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Measurement__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Measurements</relationshipLabel>
    <relationshipName>Measurements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Measurement__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MeasurementController.cls
public class MeasurementController {
	
    @AuraEnabled
    public static List<Measurement__c> getMeasurement(String recordId){
        
        List<Measurement__c> listMeasurement = [SELECT Id, Lead__c,Lead__r.Name, Color__c, Product__c,Product__r.Name, Glass_Type__c, Quantity__c FROM Measurement__c where lead__c =: recordId];
        return listMeasurement;
    }
    
    @AuraEnabled
         public static string updateMeasurement(Object inputData) {
             List<Measurement__c> measurementForUpdate = (List<Measurement__c>) JSON.deserialize(JSON.serialize(inputData),List<Measurement__c>.class);
          try {
                update measurementForUpdate;
               return 'Success: Measurement updated successfully';
              }
          catch (Exception e) {
               return 'The following exception has occurred: ' + e.getMessage();
         }
    }
}